### ISSUE TITLE
Couldn't load project ReactNativeAdsFacebook.xcodeproj

### ISSUE THREAD

**Issue by leo7r** [Suraj-Tiwari/react-native-ads-facebook#1]
**Describe the bug**
I'm getting the message `Couldn't load project ReactNativeAdsFacebook.xcodeproj` when trying to compile my project with this library. I was using react-native-fbads and switch to this because of the AdChoice icon and other improvements.

**To Reproduce**
1. Install react-native-fbads and test your project, when working fine go to step 2.
2. Follow instruction in https://github.com/Suraj-Tiwari/react-native-ads-facebook#switching-from-react-native-fbads.
3. Try to compile in XCode.
4. Errors arise

**Expected behavior**
I would expect that my project compiles successfully. I tried updating  FbAudienceNetwork.framework but same issue. It seems to be an issue with `ReactNativeAdsFacebook.xcodeproj`

**Screenshots**
https://www.dropbox.com/s/lp0aqtl828aflwx/Screen%20Shot%202018-08-27%20at%2011.37.50%20PM.png?dl=0
https://www.dropbox.com/s/ge7m6akzor63d89/Screen%20Shot%202018-08-27%20at%2011.37.25%20PM.png?dl=0

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.3
 - Browser: ?
 - Version: ?

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: iOs11.2
 - Browser ?
 - Version ?

**Comment by Suraj-Tiwari** [comment]
remove existing `FbAudienceNetwork.framework` and unlink completely 

Are you using pod? if no use pod
use this in your pod file
`pod 'FBAudienceNetwork','4.99.0'`
 then `pod install`

**Comment by leo7r** [comment]
@Suraj-Tiwari I removed `FbAudienceNetwork.framework` from project, unlinked the library and installed again `FbAudienceNetwork.framework` from pod as you say using `pod install`. Then installed library again with `react-native install react-native-ads-facebook`, try to run and get the same error.

It's something wrong with `ReactNativeAdsFacebook.xcodeproj`, when I go to project navigator in Xcode under Libraries I can click any other library and it opens the library project (targets, and so on) on the working space of xcode. When trying to open `ReactNativeAdsFacebook.xcodeproj` I get the error `This file cannot be opened`. Can you check what are the contents of your `ReactNativeAdsFacebook.xcodeproj` inside `node_modules/react-native-ads-facebook/ios/ReactNativeAdsFacebook.xcodeproj` please?

**Comment by Suraj-Tiwari** [comment]
@leo7r  After this I tried to reproduce the error, 
```
installd react-native-fbads
link react-native-fbads
used pod to install FBAudienceNetwork
```

run project `working fine`

then 
`react-native uninstall react-native-fbads` or `react-native unlink react-native-fbads` then `npm uninstall react-native-fbads`

after that `npm install react-native-ads-facebook` or `yarn add react-native-ads-facebook`
`react-native link react-native-ads-facebook`

in pod file
```
target 'fbadsPortTest' do
  pod 'FBAudienceNetwork' ,'4.99.0' //added this
end
```
after that opened `fbadsPortTest.xcworkspace` 
`Product > Clean`
'Product > Run'

everything worked fine.
Compile Success

you might have missed some point

**Comment by leo7r** [comment]
@Suraj-Tiwari I tried all the steps, same error.

I noticed that inside `node_modules/react-native-ads-facebook/ios/ReactNativeAdsFacebook.xcodeproj` it looks like this:

![image](https://user-images.githubusercontent.com/6210797/44804401-3b65cb00-ab8f-11e8-8aa2-3af187ac0f8a.png)

but other libraries have more files inside their xcodeproj (for example admob library):

![image](https://user-images.githubusercontent.com/6210797/44804479-6a7c3c80-ab8f-11e8-8a85-3f3898cbb1e2.png)

And in XCode it's the only library project that i can't click on it (notice the lack of the grey arrow in list):

![image](https://user-images.githubusercontent.com/6210797/44804577-b16a3200-ab8f-11e8-8744-332690dca790.png)

And if I click then I got this:

![image](https://user-images.githubusercontent.com/6210797/44804619-d52d7800-ab8f-11e8-9bef-2a83f8955282.png)

any idea? thanks for all your help

**Comment by Suraj-Tiwari** [comment]
Issue was due to outdated Xcode
